name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Set version from release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          bun x json -I -f package.json -e "this.version='${VERSION}'"

      - name: Build project
        run: bun run build

      - name: Publish to NPM
        run: bun publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
