name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set version from release tag
        run: |
          # Extract version from ref, removing refs/tags/ and optional v prefix
          VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
          echo "Version: $VERSION"
          # Validate semver format
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Expected semver (e.g. 1.0.0)"
            exit 1
          fi
          bun x json -I -f package.json -e "this.version='${VERSION}'"

      - name: Build project
        run: bun run build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
